config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets,  except: [:destroy, :index, :show]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("layouts.footer.rbor"), "https://www.railstutorial.org/" %>
    <%= link_to t("layouts.footer.by"), "https://www.railstutorial.org/" %>
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to t("layouts.footer.new"), "https://www.railstutorial.org/" %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts.header.sampleapp"), home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts.header.home"), root_path %></li>
        <li><%= link_to t("layouts.header.help"), help_path %></li>
        <% if logged_in?  %>
          <li><%= link_to t("layouts.header.user"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "layouts.header.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts.header.profile"), current_user %></li>
              <li><%= link_to t("layouts.header.setting"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layouts.header.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %><%= yield(:base_title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "upload_image", "data-turbolinks-track": "reload" %>
</head>
<body>
  <%= render "layouts/header" %>
    <div class="container">
      <%= link_to t(".english"), locale: :en %>
      <%= link_to t(".vietnamese"), locale: :vi %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message,
          class: "err alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
  </div>
  <body>
</html>